# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      working-directory: .
      run: ./gradlew build -x test
      
    - name: Run tests
      working-directory: .
      run: ./gradlew test

  system-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Compose
        working-directory: .
        run: docker-compose up -d --build

      - uses: actions/setup-python@v1
        with:
          'python-version:3.7'
      - run: pip install pytest requests

      - name: Run system tests
        working-directory: .
        run: pytest

      - name: Bring server down
        working-directory: .
        run: docker-compose down